name: 'Deploy MkDocs project'
description: 'Easily publish your MkDocs project to GitHub Pages'
inputs:
  docs-dir:
    description: 'The directory where your MkDocs project is in'
    required: false
    default: .
  extra-packages:
    description: 'Extra pip packages you want to add. This is useful in situations where you want to use MkDocs extensions such as PyMdown Extensions'
    required: false
    default: null
runs:
  using: 'composite'
  steps:
    - run: echo Installing pip packages
      shell: bash
    - run: pip install mkdocs ${{ inputs.extra-packages }}
      shell: bash
    - run: echo Deploying
      shell: bash
    - run: mkdocs gh-deploy`
      shell: bash
      working-directory: ${{ inputs.docs-dir }}